version: "3"

services:
  axs:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7080:7080
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "10"
#    networks:
#      - wifi_auth